spring:
  datasource:
    url: jdbc:mysql://localhost/jzzz
    username: jzzzuser
    password: jzzzuserpw
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  security:
    user:
      name: jzzz-toegang-secure
      password: jzzz-toegang-secure-pw
server:
  port: 9082