spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/./thermostatsDatabase
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  autoconfigure:
  security:
    user:
      name: jzzz-leden-secure
      password: jzzz-leden-secure-pw
server:
  port: 9081

# Add these lines
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
